name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-file:
          [
            "checkout.spec.ts",
            "login.spec.ts",
            "products.spec.ts",
            "screenshot_comparison.spec.ts",
          ]

    env:
      USERNAME_SUCCESS: ${{ secrets.USERNAME_SUCCESS }}
      PASSWORD: ${{ secrets.PASSWORD }}
      NAME: ${{ secrets.NAME }}
      SURNAME: ${{ secrets.SURNAME }}
      POSTAL_CODE: ${{ secrets.POSTAL_CODE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test tests/${{ matrix.test-file }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
